[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
real = "9biT7wc4uXgp88ewNP81gqzs8qF6J4QZuXC78LjyLCST"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
